name: 'Web3 Storage Pinning GitHub Action'
description: 'Pin your ipfs cid to a Web3.Storage'
author: 'Saeta <saetaeth@proton.me>'
branding:
  icon: 'box'
  color: 'gray-dark'
inputs:
  cid:
    description: 'Ipfs cid to be pinned on Web3.Storage'
    required: true
  pin_name:
    description: 'Name of pin'
    required: true
  web3_storage_api_token:
    description: 'API Token for Web3.Storage'
    required: true
outputs:
  cid:
    description: 'Ipfs cid of the pinned file/directory'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PIN_NAME: ${{ inputs.pin_name }} 
    CID: ${{ inputs.cid }}
    WEB3_STORAGE_API_TOKEN: ${{ inputs.web3_storage_api_token }}
  