name: 'Web3.Storage Pinning'
description: 'Pin your CID to a Web3.Storage'
author: 'Alexander Schau <alexander@schau.email>'
branding:
  icon: 'box'
  color: 'gray-dark'
inputs:
  cid:
    description: 'CID v1 to be pinned on Web3.Storage'
    required: true
  access_token:
    description: 'Access Token for API Endpoint'
    required: true
outputs:
  cid:
    description: 'IPFS CID of the pinned file/directory'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CID: ${{ inputs.cid }}
    ACCESS_TOKEN: ${{ inputs.access_token }}
  